# Generated by Django 3.1.6 on 2021-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ManyToManyField(blank=True, to='api.Ratings'),
        ),
    ]
